import random
from typing import Dict
from heuristics.base import VariableHeuristic
from csp.csp_instance import CSPInstance
from csp.features import compute_all_features
from gp.individual import GPIndividual


# This class represents a heuristic generated by Genetic Programming (GP)
# It behaves like any other heuristic (DOM, DEG, etc.), but its logic is learned automatically
class GPHeuristic(VariableHeuristic):

    # Initialize the GP heuristic with:
    # a GP individual (expression tree)
    # a random seed to generate a constant value "r"
    def __init__(self, individual: GPIndividual, seed: int = 0) -> None:
        self.individual = individual  # GP expression (the learned heuristic)
        self.rng = random.Random(seed)
        self.constant_r = self.rng.uniform(-1, 1)  # random constant used in expressions

    # This function assigns a score to a variable
    # The solver will pick the variable with the smallest score
    def score(
        self,
        var: str,
        csp: CSPInstance,
        domains: Dict[str, set[int]],
        assignment: Dict[str, int],
    ) -> float:

        # Compute all features (dom, deg, conflicts, kappa) for every variable
        features_all = compute_all_features(csp, domains, assignment)

        # Extract features for the current variable
        feats = features_all[var].copy()

        # Add the random constant "r" to the feature set
        # This allows GP to use constants in its formulas
        feats["r"] = self.constant_r

        # Evaluate the GP expression tree using these features
        # This returns a numeric score for the variable
        return float(self.individual.evaluate(feats))